modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="dndsheets"
version="1.0.2"
displayName="D&D Sheets"
authors="Hawthorn, Cosmic"

[[dependencies.dndsheets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




